jobs:
  - name: test-job
    plan:
      - timeout: 6h
        get: my_repo
        params: {}
        trigger: true
        version: latest
      - timeout: 6h
        task: oci-build
        file: .ci/task/oci-build.yml
        privileged: true
    on_failure:
      timeout: 6h
      do:
        - timeout: 6h
          put: discord-ping
          params:
            text: Job "$BUILD_JOB_NAME" failed in pipeline "$BUILD_PIPELINE_NAME" -
              $ATC_EXTERNAL_URL/build/$BUILD_ID
    on_success:
      timeout: 6h
      do:
        - timeout: 6h
          put: discord-ping
          params:
            text: Job "$BUILD_JOB_NAME" succeeded in pipeline "$BUILD_PIPELINE_NAME"!
    public: false
    serial: false
groups:
  - name: my-group
    jobs:
      - test-job
resource_types:
  - name: discord-ping_resource_type
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
    privileged: false
  - name: my_repo_resource_type
    type: registry-image
    source:
      repository: concourse/git-resource
      tag: alpine
    privileged: false
resources:
  - name: discord-ping
    type: discord-ping_resource_type
    source:
      url: ((discord-webhook-url))
  - name: my_repo
    type: my_repo_resource_type
    source:
      uri: https://github.com/DecentM/concourse-ts-field-test.git
    check_every: 1m
